<a href="https://colab.research.google.com/github/mojtabaSefidi/Dataminig-small-projects/blob/main/Computational_datamining_Ex4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
from numpy import linalg as LA
import time

In [23]:
def symmetric_matrix_generator(n):
  b = np.random.randint(100, size=(n, n))
  b_symm = (b + b.T)/2
  return b_symm

In [24]:
def normalize(x):
  fac = abs(x).max()
  x_n = x / x.max()
  return fac, x_n

def max_Eigenvalue(A,k):
  x = np.ones(A.shape[0])
  for i in range(k):
      x = np.dot(A, x)
      lambda_1, x = normalize(x)  
  return lambda_1, x

def min_Eigenvalue(A,k,x):
  for i in range(k):
      x = np.dot(LA.inv(A), x)
      lambda_1, x = normalize(x)  
  return lambda_1, x
  

In [25]:
A = symmetric_matrix_generator(5)
A

array([[79. , 26. , 33. , 67. , 76.5],
       [26. , 75. , 61.5, 11. , 37.5],
       [33. , 61.5, 22. , 53. , 78. ],
       [67. , 11. , 53. , 98. , 27.5],
       [76.5, 37.5, 78. , 27.5,  0. ]])

In [26]:
w, v = LA.eig(A)

print('The eigenvalues are: \n', w)
print('\n The corresponding eigenvector are: \n', v)

The eigenvalues are: 
 [246.52310588 -83.47132288  84.94484402  32.86600491  -6.86263195]

 The corresponding eigenvector are: 
 [[-0.52459293 -0.30920612  0.25739569  0.66128802 -0.35445655]
 [-0.35585866  0.09169539 -0.72368436 -0.24258006 -0.53140608]
 [-0.43310108 -0.58004413 -0.24926334 -0.18800837  0.61521777]
 [-0.4932801   0.16753363  0.57524873 -0.61400097 -0.14387125]
 [-0.40898051  0.72901634 -0.13032685  0.30250411  0.43906298]]


In [27]:
Eigenvalue,Eigenvector = max_Eigenvalue(A,100)
    
print('Largest Eigenvalue:', Eigenvalue)
print('Eigenvector of Largest Eigenvalue:', Eigenvector)

Largest Eigenvalue: 246.5231058843797
Eigenvector of Largest Eigenvalue: [1.         0.678352   0.82559458 0.94031024 0.77961499]


In [28]:
Eigenvalue,Eigenvector = min_Eigenvalue(A,100,Eigenvector)
    
print('Smallest Eigenvalue:', Eigenvalue)
print('Eigenvector of Smallest Eigenvalue:', Eigenvector)

Smallest Eigenvalue: 0.16869866403989303
Eigenvector of Smallest Eigenvalue: [-0.57614811 -0.86376907  1.         -0.23385418  0.71367083]


In [29]:
q, r = LA.qr(A)

print('Q:', q)
print()
print('R:', r)

print()
b = np.dot(q, r)
print('QR:', b)

Q: [[-0.58323235  0.19163409 -0.54790939  0.28878882 -0.48940037]
 [-0.19194989 -0.75813885  0.37002218 -0.03075369 -0.50051825]
 [-0.2436287  -0.54583026 -0.54172797 -0.25076944  0.53512604]
 [-0.49464009  0.29910634  0.24973914 -0.77623021 -0.03104196]
 [-0.56477563  0.03326523  0.45501654  0.50023653  0.47185302]]

R: [[-135.45202103  -71.16357458 -106.67984051 -118.10639575  -84.42103642]
 [   0.          -80.90887253  -33.86255584    5.79816882  -48.11953445]
 [   0.            0.           41.48480373  -24.36387678  -63.42619192]
 [   0.            0.            0.          -56.5942756   -19.96726544]
 [   0.            0.            0.            0.          -15.32238569]]

QR: [[7.9000000e+01 2.6000000e+01 3.3000000e+01 6.7000000e+01 7.6500000e+01]
 [2.6000000e+01 7.5000000e+01 6.1500000e+01 1.1000000e+01 3.7500000e+01]
 [3.3000000e+01 6.1500000e+01 2.2000000e+01 5.3000000e+01 7.8000000e+01]
 [6.7000000e+01 1.1000000e+01 5.3000000e+01 9.8000000e+01 2.7500000e+01]
 [7.6500000e+0

In [30]:
def QR_Eigenvalue(A,p):
  for i in range(p[-1]):
      q, r = LA.qr(A)
      A = np.dot(r, q)
      if i+1 in p:
          print(f'Iteration {i+1}:')
          print(A.diagonal())

p = [1]
p += list(range(5,30,5))
QR_Eigenvalue(A,p)

Iteration 1:
[224.7492131   79.95692915 -57.41805892  33.94183067  -7.229914  ]
Iteration 5:
[246.51991688  70.39947146 -68.92045915  32.86369979  -6.86262898]
Iteration 10:
[246.52310582  72.56229001 -71.08876853  32.86600465  -6.86263195]
Iteration 15:
[246.52310588  74.42596488 -72.95244373  32.86600491  -6.86263195]
Iteration 20:
[246.52310588  76.02517619 -74.55165505  32.86600491  -6.86263195]
Iteration 25:
[246.52310588  77.39288403 -75.91936289  32.86600491  -6.86263195]


In [31]:
def lanczos(A,v=None,k=None):

  if k == None:
    k=len(A) 
  V = [] 
  T = np.zeros((k, k))
  if v == None:
    v = np.random.rand(len(A), 1) 
  elif v != None and v.shape != (len(A), 1):
    v  = v.reshape(len(A), 1)
  v_norm = np. linalg.norm(v, 2) 
  if v_norm != 1:
    v = v / v_norm 
  V.append(v)

  w_prime = np.matmul(A, v) 
  a = np.matmul(np.transpose(w_prime), v)
  w = w_prime - a*v 
  T[0][0] = a

  for i in range(1, k):
    b = np.linalg.norm(w)
    if b != 0:
      v = w / b
      V.append(v)
    else:
      z = np.zeros(O.shape[1] + 1)
      z[-1] = 1
      v = np.linalg.lstsa(np.hstack((np.array(V), np.random.rand(len(A), 1))), z)[0]
      V.append()
    w_prime = np.matmul(A, v)
    a = np.matmul(np.transpose(w_prime), v)
    W = w_prime - a*v - b*V[i-1] 
    T[i][i-1]= b 
    T[i-1][i] = b 
    T[i][i] = a
  return LA.eig(T)[0]


In [34]:
print('The eigenvalues are: \n', lanczos(A))

The eigenvalues are: 
 [-112.72009402  -23.24763604  265.63322948   93.93636802  201.62684798]


In [12]:
def QR_Eigenvalue(A,p):
  for i in range(p[-1]):
      q, r = LA.qr(A)
      A = np.dot(r, q)
  return A.diagonal()

p = [1]
p += list(range(5,30,5))


In [13]:
A = symmetric_matrix_generator(100)

start_time = time.time()
LA.eig(A)
print('Numpy built-in function runtime on 100*100 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
max_Eigenvalue(A,25)
print('Power Method runtime on 100*100 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
QR_Eigenvalue(A,p)
print('QR algortithm runtime on 100*100 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
lanczos(A)
print('lanczos algortithm runtime on 100*100 matrix:',round((time.time() - start_time),2),'s')



Numpy built-in function runtime on 100*100 matrix: 0.02 s
Power Method runtime on 100*100 matrix: 0.0 s
QR algortithm runtime on 100*100 matrix: 0.04 s
lanczos algortithm runtime on 100*100 matrix: 0.02 s


In [14]:
A = symmetric_matrix_generator(500)

start_time = time.time()
LA.eig(A)
print('Numpy built-in function runtime on 500*500 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
max_Eigenvalue(A,25)
print('Power Method runtime on 500*500 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
QR_Eigenvalue(A,p)
print('QR algortithm runtime on 500*500 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
lanczos(A)
print('lanczos algortithm runtime on 500*500 matrix:',round((time.time() - start_time),2),'s')



Numpy built-in function runtime on 500*500 matrix: 0.38 s
Power Method runtime on 500*500 matrix: 0.0 s
QR algortithm runtime on 500*500 matrix: 1.2 s
lanczos algortithm runtime on 500*500 matrix: 0.66 s


In [15]:
A = symmetric_matrix_generator(1000)

start_time = time.time()
LA.eig(A)
print('Numpy built-in function runtime on 1000*1000 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
max_Eigenvalue(A,25)
print('Power Method runtime on 1000*1000 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
QR_Eigenvalue(A,p)
print('QR algortithm runtime on 1000*1000 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
lanczos(A)
print('lanczos algortithm runtime on 1000*1000 matrix:',round((time.time() - start_time),2),'s')



Numpy built-in function runtime on 1000*1000 matrix: 1.93 s
Power Method runtime on 1000*1000 matrix: 0.02 s
QR algortithm runtime on 1000*1000 matrix: 6.82 s
lanczos algortithm runtime on 1000*1000 matrix: 2.86 s


In [16]:
A = symmetric_matrix_generator(2500)

start_time = time.time()
LA.eig(A)
print('Numpy built-in function runtime on 2500*2500 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
max_Eigenvalue(A,25)
print('Power Method runtime on 2500*2500 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
QR_Eigenvalue(A,p)
print('QR algortithm runtime on 2500*2500 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
lanczos(A)
print('lanczos algortithm runtime on 2500*2500 matrix:',round((time.time() - start_time),2),'s')



Numpy built-in function runtime on 2500*2500 matrix: 23.99 s
Power Method runtime on 2500*2500 matrix: 0.13 s
QR algortithm runtime on 2500*2500 matrix: 89.18 s
lanczos algortithm runtime on 2500*2500 matrix: 40.85 s


In [17]:
A = symmetric_matrix_generator(5000)

start_time = time.time()
LA.eig(A)
print('Numpy built-in function runtime on 5000*5000 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
max_Eigenvalue(A,25)
print('Power Method runtime on 5000*5000 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
QR_Eigenvalue(A,p)
print('QR algortithm runtime on 5000*5000 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
lanczos(A)
print('lanczos algortithm runtime on 5000*5000 matrix:',round((time.time() - start_time),2),'s')



Numpy built-in function runtime on 5000*5000 matrix: 151.58 s
Power Method runtime on 5000*5000 matrix: 0.52 s
QR algortithm runtime on 5000*5000 matrix: 649.87 s
lanczos algortithm runtime on 5000*5000 matrix: 296.44 s


In [18]:
A = symmetric_matrix_generator(10000)

start_time = time.time()
LA.eig(A)
print('Numpy built-in function runtime on 10000*10000 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
max_Eigenvalue(A,25)
print('Power Method runtime on 10000*10000 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
lanczos(A)
print('lanczos algortithm runtime on 10000*10000 matrix:',round((time.time() - start_time),2),'s')



Numpy built-in function runtime on 10000*10000 matrix: 1113.4 s
Power Method runtime on 10000*10000 matrix: 1.91 s
lanczos algortithm runtime on 10000*10000 matrix: 2167.3 s


In [21]:
import pandas as pd
conclusion = pd.DataFrame([['100 * 100',0.02 ,0,0.04,0.02],
              ['500 * 500',0.38 ,0,1.2,0.66],
              ['1000 * 1000',1.93 ,0.02,6.82,2.86],
              ['2500 * 2500',23.99 ,0.13,89.18,40.85],
              ['5000 * 5000',151.58 ,0.52,649.87,296.44],
              ['10000 * 10000',1113.4,1.91,'runtime error',2167.3]],
              columns=['Dimension of Matrix',"Numpy Built-in Function","Power Method","QR Algortithm","lanczos Algortithm"])
conclusion



Dimension of Matrix  Numpy Built-in Function  Power Method  QR Algortithm  \
0           100 * 100                     0.02          0.00           0.04   
1           500 * 500                     0.38          0.00            1.2   
2         1000 * 1000                     1.93          0.02           6.82   
3         2500 * 2500                    23.99          0.13          89.18   
4         5000 * 5000                   151.58          0.52         649.87   
5       10000 * 10000                  1113.40          1.91  runtime error   

   lanczos Algortithm  
0                0.02  
1                0.66  
2                2.86  
3               40.85  
4              296.44  
5             2167.30