<a href="https://colab.research.google.com/github/mojtabaSefidi/Dataminig-small-projects/blob/main/Computational_datamining_Ex5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_classification
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import Pipeline
from numpy.linalg import svd
from sklearn import svm
from numpy import mean
from numpy import std
from numpy import dot
import numpy as np
import time

In [47]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print('A is:\n', A)

U, s, VT = svd(A)
print()
print('U is:\n', U)
print()
print('S is:\n', s)
print()
print('VT is:\n', VT)

A is:
 [[1 2]
 [3 4]
 [5 6]]

U is:
 [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

S is:
 [9.52551809 0.51430058]

VT is:
 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [49]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print('A is:\n', A)

U, s, VT = svd(A)
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:A.shape[1], :A.shape[1]] = np.diag(s)
print()
B = U.dot(Sigma.dot(VT))
print('B is:\n', B)

A is:
 [[1 2]
 [3 4]
 [5 6]]

B is:
 [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [51]:
A = np.array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print('A is:\n', A)
print()

U, s, VT = svd(A)
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:A.shape[0], :A.shape[0]] = np.diag(s)
n_elements = 2
Sigma = Sigma[:, :n_elements]
VT = VT[:n_elements, :]

B = U.dot(Sigma.dot(VT))
print('B is:\n',B)
print()

T = U.dot(Sigma)
print('T is:\n',T)
print()

T = A.dot(VT.T)
print('Reconstructed T is:\n',T)

A is:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

B is:
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]]

T is:
 [[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]

Reconstructed T is:
 [[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [53]:
A = np.array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print('A is:\n', A)
print()

svd = TruncatedSVD(n_components=2)
svd.fit(A)
result = svd.transform(A)
print('T is:\n',result)

A is:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]

T is:
 [[18.52157747  6.47697214]
 [49.81310011  1.91182038]
 [81.10462276 -2.65333138]]


In [60]:
X, y = make_classification(n_samples=10000, n_features=20, n_informative=15, n_redundant=5, random_state=7)
print(X.shape, y.shape)

(10000, 20) (10000,)


In [61]:
start_time = time.time()
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(svm.SVC(), X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
print('Time duration before using TruncatedSVD:',round((time.time() - start_time),2),'s')
print('Accuracy before using TruncatedSVD: %.3f' % (mean(n_scores)))

Time duration before using TruncatedSVD: 29.51 s
Accuracy before using TruncatedSVD: 0.986


In [62]:
start_time = time.time()
steps = [('svd', TruncatedSVD(n_components=10)), ('m', svm.SVC())]
model = Pipeline(steps=steps)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
print('Time duration After using TruncatedSVD:',round((time.time() - start_time),2),'s')
print('Accuracy After using TruncatedSVD: %.3f' % (mean(n_scores)))

Time duration After using TruncatedSVD: 28.7 s
Accuracy After using TruncatedSVD: 0.962


In [63]:
X, y = make_classification(n_samples=10000, n_features=100, n_informative=15, n_redundant=5, random_state=7)
print(X.shape, y.shape)

(10000, 100) (10000,)


In [64]:
start_time = time.time()
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(svm.SVC(), X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
print('Time duration before using TruncatedSVD:',round((time.time() - start_time),2),'s')
print('Accuracy before using TruncatedSVD: %.3f' % (mean(n_scores)))

Time duration before using TruncatedSVD: 57.88 s
Accuracy before using TruncatedSVD: 0.980


In [65]:
start_time = time.time()
steps = [('svd', TruncatedSVD(n_components=10)), ('m', svm.SVC())]
model = Pipeline(steps=steps)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
print('Time duration After using TruncatedSVD:',round((time.time() - start_time),2),'s')
print('Accuracy After using TruncatedSVD: %.3f' % (mean(n_scores)))

Time duration After using TruncatedSVD: 30.21 s
Accuracy After using TruncatedSVD: 0.961


In [66]:
X, y = make_classification(n_samples=10000, n_features=500, n_informative=15, n_redundant=5, random_state=7)
print(X.shape, y.shape)

(10000, 500) (10000,)


In [67]:
start_time = time.time()
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(svm.SVC(), X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
print('Time duration before using TruncatedSVD:',round((time.time() - start_time),2),'s')
print('Accuracy before using TruncatedSVD: %.3f' % (mean(n_scores)))

Time duration before using TruncatedSVD: 639.68 s
Accuracy before using TruncatedSVD: 0.957


In [68]:
start_time = time.time()
steps = [('svd', TruncatedSVD(n_components=10)), ('m', svm.SVC())]
model = Pipeline(steps=steps)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
print('Time duration After using TruncatedSVD:',round((time.time() - start_time),2),'s')
print('Accuracy After using TruncatedSVD: %.3f' % (mean(n_scores)))

Time duration After using TruncatedSVD: 35.42 s
Accuracy After using TruncatedSVD: 0.962


In [69]:
X, y = make_classification(n_samples=10000, n_features=1000, n_informative=15, n_redundant=5, random_state=7)
print(X.shape, y.shape)

(10000, 1000) (10000,)


In [ ]:
start_time = time.time()
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(svm.SVC(), X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
print('Time duration before using TruncatedSVD:',round((time.time() - start_time),2),'s')
print('Accuracy before using TruncatedSVD: %.3f' % (mean(n_scores)))

Time duration before using TruncatedSVD: 1038.59 s
Accuracy before using TruncatedSVD: 0.931


In [71]:
start_time = time.time()
steps = [('svd', TruncatedSVD(n_components=10)), ('m', svm.SVC())]
model = Pipeline(steps=steps)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')
print('Time duration After using TruncatedSVD:',round((time.time() - start_time),2),'s')
print('Accuracy After using TruncatedSVD: %.3f' % (mean(n_scores)))

Time duration After using TruncatedSVD: 42.17 s
Accuracy After using TruncatedSVD: 0.962


In [81]:
import pandas as pd
conclusion = pd.DataFrame([['(10000, 20)',29.51 ,0.986,28.7,0.962],
              ['(10000, 100)',57.88 ,0.980,30.21,0.961],
              ['(10000, 500)',639.68 ,0.957,35.42,0.962],
              ['(10000, 1000)',1038.59 ,0.931,42.17,0.962]],
              columns=['Dimension of Matrix',"Time duration","Time duration After TruncatedSVD","Acuuracy","Acuuracy After TruncatedSVD"])
conclusion



Dimension of Matrix  Time duration  Time duration After TruncatedSVD  \
0         (10000, 20)          29.51                             0.986   
1        (10000, 100)          57.88                             0.980   
2        (10000, 500)         639.68                             0.957   
3       (10000, 1000)        1038.59                             0.931   

   Acuuracy  Acuuracy After TruncatedSVD  
0     28.70                        0.962  
1     30.21                        0.961  
2     35.42                        0.962  
3     42.17                        0.962

In [76]:
def CUR(A, n): 
    A_sq = A ** 2
    sum_A_sq = np.sum(A_sq)
    sum_A_sq_0 = np.sum(A_sq, axis=0)
    sum_A_sq_1 = np.sum(A_sq, axis=1)
    
    P_x_c = sum_A_sq_0 / sum_A_sq
    P_x_r = sum_A_sq_1 / sum_A_sq
    
    r, c = A.shape
    
    c_index = [np.random.choice(np.arange(0, c), p=P_x_c) for i in range(n)]
    r_index = [np.random.choice(np.arange(0, r), p=P_x_r) for i in range(n)]
#     print(c_index, r_index)
    C = A[:, c_index]
    R = A[r_index, :]
    W = C[r_index]
#     print(C, R, W)

    X, sigma, Y = linalg.svd(W, n)
    for i in range(len(sigma)):
        if sigma[i] == 0:
            continue
        else:
            sigma[i] = 1 / sigma[i]
    sigma = np.diag(sigma)
    U = np.dot(np.dot(Y, sigma), X.T)
    return np.dot(np.dot(C, U), R)

In [77]:
A = np.linspace(0, 14, 15).reshape((3, -1))
A

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [78]:
CUR(A, 3)

array([[0.9375 , 0.53125, 0.625  , 0.21875, 0.8125 ],
       [1.875  , 2.0625 , 0.25   , 0.4375 , 1.625  ],
       [1.75   , 3.625  , 4.5    , 3.375  , 4.25   ]])