<a href="https://colab.research.google.com/github/mojtabaSefidi/Dataminig-small-projects/blob/main/Computational_datamining_Ex3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# QR Decomposition Functions

In [20]:
from math import copysign, hypot
import numpy as np
import time

## Gram Schmidt

In [2]:
def gram_schmidt_process(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]

        for i in range(j - 1):
            q = Q[:, i]
            R[i, j] = q.dot(v)
            v = v - R[i, j] * q

        norm = np.linalg.norm(v)
        Q[:, j] = v / norm
        R[j, j] = norm
    return Q, R

## Gram Schmidt Test

In [3]:
# Input matrix
A = np.array([[12, -51, 4],
             [6, 167, -68],
             [-4, 24, -41]], dtype=np.float64)

# Print input matrix
print('A is: \n', A)

# Compute QR decomposition using Givens rotation
(Q, R) = gram_schmidt_process(A)

# Print orthogonal matrix Q
print('\n Q is: \n', Q)

# Print upper triangular matrix R
print('\n R is: \n', R)

A is: 
 [[ 12. -51.   4.]
 [  6. 167. -68.]
 [ -4.  24. -41.]]

 Q is: 
 [[ 0.85714286 -0.28935268  0.2044405 ]
 [ 0.42857143  0.94748818 -0.79220694]
 [-0.28571429  0.13616597 -0.57498891]]

 R is: 
 [[ 14.           0.         -14.        ]
 [  0.         176.25549637   0.        ]
 [  0.           0.          78.26237921]]


## Givens Rotation

In [11]:
def _givens_rotation_matrix_entries(a, b):
    r = hypot(a, b)
    c = a/r
    s = -b/r
    return (c, s)

def givens_rotation(A):
    (num_rows, num_cols) = np.shape(A)
    Q = np.identity(num_rows)
    R = np.copy(A)
    (rows, cols) = np.tril_indices(num_rows, -1, num_cols)
    for (row, col) in zip(rows, cols):
        if R[row, col] != 0:
            (c, s) = _givens_rotation_matrix_entries(R[col, col], R[row, col])
            G = np.identity(num_rows)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)
            Q = np.dot(Q, G.T)
    return (Q, R)


In [16]:
np.set_printoptions(precision=4, suppress=True)

# Input matrix
A = np.array([[6, 5, 0],
              [5, 1, 4],
              [0, 4, 3]])

# Print input matrix
print('A is: \n', A)

# Compute QR decomposition using Givens rotation
(Q, R) = givens_rotation(A)

# Print orthogonal matrix Q
print('\n Q is: \n', Q)

# Print upper triangular matrix R
print('\n R is: \n', R)

A is: 
 [[6 5 0]
 [5 1 4]
 [0 4 3]]

 Q is: 
 [[ 0.7682  0.3327  0.547 ]
 [ 0.6402 -0.3992 -0.6564]
 [ 0.      0.8544 -0.5196]]

 R is: 
 [[ 7.8102  4.4813  2.5607]
 [ 0.      4.6817  0.9664]
 [ 0.      0.     -4.1843]]


## Runtime Analysis

In [27]:
np.set_printoptions(precision=4, suppress=True)
A = np.random.standard_normal(size=(100, 100))

start_time = time.time()
(Q, R) = givens_rotation(A)
print('givens_rotation algortithm runtime on 100*100 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
(Q, R) = gram_schmidt_process(A)
print('gram_schmidt_process algortithm runtime on 100*100 matrix:',round((time.time() - start_time),2),'s')



givens_rotation algortithm runtime on 100*100 matrix: 1.46 s
gram_schmidt_process algortithm runtime on 100*100 matrix: 0.04 s


In [33]:
np.set_printoptions(precision=4, suppress=True)
A = np.random.standard_normal(size=(250, 250))

start_time = time.time()
(Q, R) = givens_rotation(A)
print('givens_rotation algortithm runtime on 250*250 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
(Q, R) = gram_schmidt_process(A)
print('gram_schmidt_process algortithm runtime on 250*250 matrix:',round((time.time() - start_time),2),'s')


givens_rotation algortithm runtime on 250*250 matrix: 84.87s
gram_schmidt_process algortithm runtime on 250*250 matrix: 0.21s


In [34]:
np.set_printoptions(precision=4, suppress=True)
A = np.random.standard_normal(size=(400, 400))

start_time = time.time()
(Q, R) = givens_rotation(A)
print('givens_rotation algortithm runtime on 400*400 matrix:',round((time.time() - start_time),2),'s')

start_time = time.time()
(Q, R) = gram_schmidt_process(A)
print('gram_schmidt_process algortithm runtime on 400*400 matrix:',round((time.time() - start_time),2),'s')

givens_rotation algortithm runtime on 400*400 matrix: 747.56s
gram_schmidt_process algortithm runtime on 400*400 matrix: 0.47s


In [35]:
A = np.random.standard_normal(size=(1000, 1000))
start_time = time.time()
(Q, R) = gram_schmidt_process(A)
print('gram_schmidt_process algortithm runtime on 1000*1000 matrix:',round((time.time() - start_time),2),'s')

gram_schmidt_process algortithm runtime on 1000*1000 matrix: 7.73s


In [36]:
A = np.random.standard_normal(size=(2500, 2500))
start_time = time.time()
(Q, R) = gram_schmidt_process(A)
print('gram_schmidt_process algortithm runtime on 2500*2500 matrix:',round((time.time() - start_time),2),'s')



gram_schmidt_process algortithm runtime on 2500*2500 matrix: 43.55s


In [37]:
np.set_printoptions(precision=4, suppress=True)
A = np.random.standard_normal(size=(5000, 5000))
start_time = time.time()
(Q, R) = gram_schmidt_process(A)
print('gram_schmidt_process algortithm runtime on 100*100 matrix:',round((time.time() - start_time),2),'s')



gram_schmidt_process algortithm runtime on 2500*2500 matrix: 1780.26 s


In [41]:
import pandas as pd
conclusion = pd.DataFrame([['100 * 100',0.04 ,1.46],
              ['250 * 250',0.21 ,84.87],
              ['400 * 400',0.47 ,747.56],
              ['1000 * 1000',7.73 ,'runtime error'],
              ['2500 * 2500',43.55 ,'runtime error'],
              ['5000 * 5000',1780.26 ,'runtime error']],
              columns=['Dimension of Matrix',"Gram schmidt process","Givens Rotation"])
conclusion



Dimension of Matrix  Gram schmidt process Givens Rotation
0           100 * 100                  0.04            1.46
1           250 * 250                  0.21           84.87
2           400 * 400                  0.47          747.56
3         1000 * 1000                  7.73   runtime error
4         2500 * 2500                 43.55   runtime error
5         5000 * 5000               1780.26   runtime error