<a href="https://colab.research.google.com/github/mojtabaSefidi/Dataminig-small-projects/blob/main/Computational_datamining_Ex6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
!pip install tensorly
import numpy as np
import tensorly as tl
from tensorly.decomposition import parafac
from tensorly.decomposition import tucker
from tensorly.decomposition import matrix_product_state
from tensorly import tt_to_tensor


In [45]:
T = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

print('T is:\n', T)
print('shape of This tensor:' ,T.shape)

T is:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
shape of This tensor: (3, 3, 3)


In [46]:
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

C = A + B
print('A + B = C:\n', C)


A + B = C:
 [[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [47]:
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A - B
print('A - B = C:\n', C)

A - B = C:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [48]:
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])

C = A * B
print('A * B = C:\n', C)

A * B = C:
 [[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [49]:
A = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
B = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
C = A / B / 2
print('A / B / 2 = C:\n', C)

A / B / 2 = C:
 [[[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]

 [[0.5 0.5 0.5]
  [0.5 0.5 0.5]
  [0.5 0.5 0.5]]]


In [50]:
A = np.array([1,2])
B = np.array([3,4])
C = np.tensordot(A, B, axes=0)
print('A * B = C:\n', C)

A * B = C:
 [[3 4]
 [6 8]]


In [51]:
tensor = tl.tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
tensor

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
factors = parafac(tensor, rank=2)
len(factors)
factors

(weights, factors) : rank-2 CPTensor of shape (12, 12) 

In [53]:
tl.cp_to_tensor(factors)

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -3.79947183e-17, -3.79947183e-17,
        -3.79947183e-17,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00, -3.79947183e-17,
        -3.79947183e-17, -3.79947183e-17,  0.00000000e+00],
       [ 0.00000000e+00, -3.79947183e-17, -3.79947183e-17,
        -3.79947183e-17,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00, -3.79947183e-17,
        -3.79947183e-17, -3.79947183e-17,  0.00000000e+00],
       [ 0.00000000e+00, -3.79947183e-17, -3.79947183e-17,
        -3.79947183e-17,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00, -3.79947183e-17,
        -3.79947183e-17, -3.79947183e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  1.0000000

In [54]:
core, factors = tucker(tensor, rank=[2, 3])
print('core.shape:', core.shape)
print('length of factors:', len(factors))
[f.shape for f in factors]

core.shape: (2, 3)
length of factors: 2


[(12, 2), (12, 3)]

In [55]:
factors = matrix_product_state(tensor, rank=[1,2,1])
print('length of factors:', len(factors))
[f.shape for f in factors]


length of factors: 2


[(1, 12, 2), (2, 12, 1)]

In [56]:
print('Reconstruction:')
print(np.round(tt_to_tensor(factors), decimals=10))

Reconstruction:
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0. -0.]
 [-0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [-0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [-0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [-0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
